# Generated by Django 3.0.7 on 2020-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=100, unique=True)),
                ('Task', models.CharField(choices=[('First Task', 'First Task'), ('second Task', 'Second_task'), ('Third _task', 'Third_task')], max_length=200, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
