# Generated by Django 3.0.7 on 2020-09-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='Task',
            new_name='Task_choose',
        ),
    ]
